### ISSUE TITLE
Issue when deploying to Firebase

### ISSUE THREAD

**Issue by vetribalaji** [lithic-com/lithic-node#3]
I'm getting the following error when trying to deploy to Firebase.

"
Error: Error parsing triggers: Cannot find module './core'
Require stack:
- .../functions/node_modules/lithic/dist/cjs/index.js
"

The reference to core.ts is off. Can you help with this?

**Comment by rattrayalex** [comment]
Thank you for reporting; a fix has been published at version `0.0.5`.

Can you confirm that worked for you?

**Comment by vetribalaji** [comment]
Works fine now. Thanks for the fix.
