### ISSUE TITLE
client.resend not found endpoint

### ISSUE THREAD

**Issue by bbi22** [lithic-com/lithic-node#578]
https://github.com/lithic-com/lithic-node/blob/2ed4f02945a89928d850402f146525310bba3444/src/resources/events/events.ts#L80 

This line is missing `/v1` so this always return a not found error.

**Comment by dgellow** [comment]
Hi @bbi22, thanks for the report, we are looking into it.

**Comment by dgellow** [comment]
@bbi22 Sorry for the delay. I added a fix as part of the next release: https://github.com/lithic-com/lithic-node/pull/580

**Comment by dgellow** [comment]
v0.89 has been released, with the fix. Could you upgrade and try it out?
