### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by danielchalef** [lithic-com/lithic-node#8]
> If you are interested in other runtime environments, please open or upvote an issue on Github.

Adding my vote for Deno support.

**Comment by rattrayalex** [comment]
Thank you, we hope to add support for this soon! Can you say more about what you're looking for and why?

**Comment by danielchalef** [comment]
We're using Supabase functions for our backend. I've hacked up interim solutions using `axiod` (`axios` for Deno) to make requests to your API and copied the Lithic SDK's interface definitions for type safety.

**Comment by rattrayalex** [comment]
@danielchalef sorry for the delayed response – I believe Deno should be supported now simply with `import Lithic from 'npm:lithic'` – can you check and let us know?
