### ISSUE TITLE
Maintaining through Q1 updates?

### ISSUE THREAD

**Issue by nickisobrien** [lithic-com/lithic-node#9]
What is the migration plan for this package through the Q1 updates documented [here](https://docs.lithic.com/docs/guide-to-q1-2023-lithic-api-changes)?

**Comment by rattrayalex** [comment]
@nickisobrien We've just released a version of the SDK which reflects both the current API and types for the upcoming changes! You can use this to help with the migration, following the documentation you linked.

Once the API changes are enacted, we'll release a new version reflecting them.
